language: java
jdk:
- openjdk8
notifications:
 email: false

addons:
  sonarcloud:
    organization: "simobenny8"
    token: 
       secure: "o69ph4Hn8SW2ANfYXII0mTuqGoGNnLRLQxiAHJitZ+wy9R5t1UOeHNTdvs9IWdlNsaI+K5n/bWgs3YUMdLg+y807mdA1maKzr5mvh+d2fkwQX4KPVuxT+kKuKZSLjkzvzkKw9zyIMB7+woayIQSqGS98MfXPuECIAP6khMj3g/faNm2UjvpSK/qbwe1njXH1Q0Hh4rpC8swroeXQwznc9k+pwDTtOw9FOjrYMmDjyF/3Nu9L+omrDIfWlcsSMCYkulux3Pe0raCuRyZMzfSWqt78k7KSaCxVJOSb2yfXYCGmU6nVgMs5JsLu2mEvMU+6x/qkdXoz2a63qsPOyPhQ5YLoMVranVeR1SYpLL8q4rTEoR0R7bwQIqWKExlLQpabnpNP+4z+E656qKyspdwEpFnklFoWvuPuhY1JeN33UI3YiZFeDHuze+A/AXjHEryulLG+/Tb0bWsnfq+jqZ895rygEJUt/s6bolxVfhuYxqJXosLCwKNMabbBTfEViZV7cHtab0mm0xEQPztxTv1UC0MJKpY9i0mgDTN59eka2g6NglouuQfMEagfIO7WssnsftABYB0Z6IfAqNsji8OcX+o7uMTi6Rp3z28CR4W+IoULIUMPyR9e/aMKVdEyd+PhjyerOXGHHmrUOdCGfbOsiXKasOaKBFfmU2Xg7LRU4XE="
script:  
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=SimoBenny8_storm