language: java
jdk:
- openjdk8
notifications:
 email: false

addons:
  sonarcloud:
    organization: "simobenny8"
    token:
        secure:"gEchOaQz2IVoHznjKOO+2VK2LafomyDHoGD2QEznDMZz8v8rM+k16LHwEiRkfYmnJBWyAPjOFLh/Y/1+r0KWbjiIwjW2Cig2fis1eaXpVQziVpyN08uDTf5e39O2AHJuv1oniGji1a2ekGR5qh+jzwpgtGZzOYtGVbviq2tsqA+85r12UXcQ54UyXmEEKJ/ik0oT74vLY5pM8uv/g6EVYpfuehDUAxk/RGQ85k3PiHhxbkufvGgJkBhd7e+ncxsEkzvFwBOwufh+fjK6IWgvSGf3wJtgl1uivsS9EV7olxZFaxl8krSUB+A5T1Yo05u+v1zm3YgS84f4Md4LYI1KzJxR/nSSCSe8LSUdMePhSB36TcEcfKxsK7VL8L4r053Gfy25hkcyjPgjXLev06TfzyFDz6zYSdvG1bSHecIpIuzNX4qEctgpWv9YaQpxRycpRdrXt74fX69d0A8+KWGcBPUiFjKj/E8gFiLFy4AtbCjC2f2NeAhVBh+3VJq3+zw5wszUctODMHNDwS0Vq4+KH5AiTIlhESxXcJ5SD9Ox+gIASVtZWux+aUyjHKuxdIfg879RsA+AgSLm+PCXk3Uvq5Aqs51hYl5p6an0YCyOPliD6uJnHcOJsgHnCXQa2Hpqz6+htpupfIEkeOPu+EL+9jQQP4Ys+1fortqXzWGd4vI="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #- mvn -Dsonar.coverage.jacoco.xmlReportPaths=C:\Users\Simone Benedetti\Documents\Programmazione JAVA\storm\moduleForJacoco\target\site\jacoco-aggregate\jacoco.xml clean verify sonar:sonar 
  # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=SimoBenny8_storm
  - mvn clean verify sonar:sonar


