language: java
jdk:
- openjdk8
notifications:
 email: false

addons:
  sonarcloud:
    organization: "SimoBenny8"
    token: 
       secure: "e2QbrJKTu2c0UW7pb0uMhvYaIlWh3tKwZPRla6MTAsNGGIDTq8YB4Obj3QwQ67Ovpi71uGP99/sxZzJivQQjPWPoEY9LjbUZmT/g1b/GbyDyr1ZzSdB5Ut/VP5l/R/J11hieMGUs1rIJ29X/4Rk4+UUdwN6Y3ECQm7HgeLIt13FN1cnKmIP3HRu9pPQFeGHiUytFMXn03j00IJRDb4UzIJ7a0jGLgbPbTmuMY+jZH+csLshdzjEBhrqeeDy9Q3AwXsrUBj3S1Zu1nkTjTyq7XMVrfsKSu42gYAFHfoK6BzuGE5AzHYV3ox4FnHUCRsmc1Ec1ZPAjCPV/VS7tazZwH3RVvnBR/PHlLcmLAsNI3wkYIQKD/F2YMA+Pj8F1+tqlC1xcOsYoW7FMq0vOFz6LLcr2TjIdFXuLaFFSVRC1kpxAMSC8OMOoeKx6d4MAVsx99s8WUV5D4hfiwlHRRxsJKT7B2nTKbwIINvD3P5HiNVjR4xztpkfgCwaALCaHBSsDqIDMYFYZ3yILZGh7wxSaixmsKbY6UF1ypCzb+UIclEMuacsNXJRhRE2QjeWw4jQN8bA7xC+2IrxuQlTgi2Xdym09UrOAUokgKX2WgPplZquSxLrqj5aFCfHRj2e3p0qzprfI8nU1dxGy8NFwnuKff4WcsZ1SbI1UxOfeWkOjd2M="
script:    
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=SimoBenny8_storm